//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemaVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchemaVersion()
        {
            this.ProductSchemas = new HashSet<ProductSchema>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SchemaID { get; set; }
        public string Version { get; set; }
    
        public virtual ASMLSchema ASMLSchema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSchema> ProductSchemas { get; set; }
    }
}
