//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasted
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductVersion { get; set; }
        public string CompName { get; set; }
        public string CompVersion { get; set; }
    }
}
